[build.environment]
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.142.0"
NODE_VERSION = "22"
TZ = "America/Los_Angeles"

[build]
base = "my-site"
publish = "public"
command = "git config core.quotepath false && hugo --gc --minify"

